"""Bilingual, offline help shared by desktop, Android and the web prototype.

Copy is written here once; scripts/export_help.py produces browser assets.
No UI dependency and no generated aviation data.
"""

def pair(fr, en):
    return {'fr': fr, 'en': en}


def step(title_fr, title_en, fr, en, target=''):
    return {'title': pair(title_fr, title_en), 'text': pair(fr, en), 'target': target}


TOPICS = [
    {'id': 'flight', 'title': pair('Votre vol', 'Your flight'), 'steps': [
        step('Un espace pour préparer', 'A place to prepare', 'Commencez par la compagnie, le callsign et les deux aéroports. Vous pouvez préparer un vol et son carburant sans créer de message ATC.', 'Start with the airline, callsign and both airports. You can prepare a flight and its fuel without creating an ATC message.', 'departure_icao'),
        step('Choisir votre avion', 'Choose your aircraft', 'Ouvrez la liste des avions RFS, puis cherchez le modèle et sa variante. Un avion importé du Finder reste modifiable. Le Fuel Helper reprend cette sélection quand elle correspond à une variante connue.', 'Open the RFS aircraft list, then search for the model and variant. You can change an aircraft imported from Finder. Fuel Helper reuses the selection when it matches a known variant.', 'aircraft'),
        step('Les valeurs que vous connaissez', 'Values you know', 'Ajoutez les portes, pistes, niveau de vol et durée totale selon votre session RFS. Une piste répertoriée ne constitue pas une affectation ATC et la base ne fournit pas de portes. Ne devinez pas une information absente.', 'Add gates, runways, flight level and total duration for your RFS session. A listed runway is not an ATC assignment and the database has no gates. Do not guess unavailable information.', 'estimated_flight_time'),
        step('Pilotes et carnet', 'Pilots and logbook', 'Ajoutez vos pilotes et leurs préférences pour les opérations en groupe ou décalées. Sur Android, Démarrer, Pause et Terminer enregistrent votre temps de vol. Les recherches seules ne comptent pas comme des vols effectués.', 'Add pilots and their preferences for group or staggered operations. On Android, Start, Pause and Complete record your flight time. Searches alone never count as completed flights.')
    ]},
    {'id': 'messages', 'title': pair('Messages', 'Messages'), 'steps': [
        step('Le bon moment du vol', 'The right flight stage', 'Choisissez le type de message, puis votre pseudo RFS. ATC REQUEST prépare le départ, AIRBORNE le vol, ARRIVAL BOARD l’approche et FLIGHT COMPLETED le bilan. Android propose aussi PUSHBACK, TAXI et ATIS ; DISPATCH FORM prépare le dossier. ATC ACTIVE et ATC OFFLINE annoncent votre position de contrôle ; FLIGHT PLAN présente le plan de vol.', 'Choose a message type, then your RFS name. ATC REQUEST prepares departure, AIRBORNE covers flight, ARRIVAL BOARD covers approach and FLIGHT COMPLETED summarises arrival. Android also has PUSHBACK, TAXI and ATIS; DISPATCH FORM prepares the briefing. ATC ACTIVE and ATC OFFLINE announce your control position; FLIGHT PLAN presents the flight plan.'),
        step('Seulement les options utiles', 'Only useful options', 'Les champs changent avec le type choisi. Les cases affichent les détails utiles : STAR, altitude, ETE, contrôleur ou absence d’ATC. Go-around prépare une remise de gaz, selon les options du message.', 'Fields change with the selected type. Checkboxes show useful details: STAR, altitude, ETE, controller or no ATC. Go-around prepares a missed approach using the message options.'),
        step('ETE : temps restant', 'ETE: time remaining', 'Dans ARRIVAL BOARD, ETE 5 min signifie une arrivée prévue dans environ cinq minutes. Ce champ est distinct de la durée totale utilisée pour calculer le carburant.', 'In ARRIVAL BOARD, ETE 5 min means arrival in approximately five minutes. This field is separate from the total duration used to calculate fuel.', 'arrival_ete'),
        step('Un message à votre style', 'A message in your style', 'Ouvrez Présentation pour changer design, longueur, emojis et alignement Discord. Les designs personnels se créent dans les paramètres sur Android. Générer remplace vos retouches de l’aperçu : copiez-les d’abord si vous voulez les garder.', 'Open Presentation to change the design, length, emojis and Discord alignment. Create custom designs in Android settings. Generate replaces your preview edits: copy them first if you want to keep them.')
    ]},
    {'id': 'preview', 'title': pair('Aperçu et copie', 'Preview and copying'), 'steps': [
        step('Relisez votre texte', 'Review your text', 'L’aperçu est modifiable. Vos retouches sont conservées jusqu’à une nouvelle génération ou une modification des données utilisées. L’application n’envoie jamais le message automatiquement.', 'The preview is editable. Edits are retained until regeneration or a change to the source fields. The app never sends your message automatically.'),
        step('Un avertissement vous guide', 'A warning guides you', 'Appuyez sur un avertissement pour ouvrir la rubrique et placer le curseur sur le champ concerné. Les limites de longueur et d’emojis vous renvoient à l’aperçu pour raccourcir le texte.', 'Tap a warning to open the section and focus the relevant field. Length and emoji limits take you to the preview so you can shorten the text.'),
        step('Vous choisissez les restrictions', 'You choose the checks', 'Vérifier avant copie est activé au départ. Désactivez-le pour copier un texte incomplet tel quel. Les avertissements restent visibles et le choix est sauvegardé. Un aperçu vide ne peut pas être copié.', 'Check before copying is initially enabled. Disable it to copy incomplete text as-is. Warnings remain visible and your choice is saved. An empty preview cannot be copied.'),
        step('Copier, puis coller', 'Copy, then paste', 'Copier place le texte dans le presse-papiers : ouvrez Discord ou RFS et collez-le. Android propose aussi Partager. Une copie réussie crée une entrée dans votre historique local.', 'Copy puts the text on the clipboard: open Discord or RFS and paste it. Android also offers Share. A successful copy creates a local history entry.')
    ]},
    {'id': 'finder', 'title': pair('Flight Finder', 'Flight Finder'), 'steps': [
        step('Chercher dans les données locales', 'Search local data', 'Choisissez une compagnie, un aéroport ou des pays de départ et d’arrivée. Les profils proviennent de la base locale, sans recherche Internet. Ils représentent des observations historiques, pas les horaires actuels.', 'Choose an airline, an airport or origin and destination countries. Profiles come from the local database without an Internet search. They represent historical observations, not current schedules.'),
        step('Affiner sans tout remplir', 'Refine without filling everything', 'Les filtres avancés permettent de préciser avion RFS, durée, distance et horaires. Dans les durées minimum, maximum et cible, 10 signifie dix heures ; 90min signifie quatre-vingt-dix minutes. Élargissez les filtres si aucun résultat ne correspond.', 'Advanced filters refine the RFS aircraft, duration, distance and times. In minimum, maximum and target duration, 10 means ten hours; 90min means ninety minutes. Broaden filters if nothing matches.'),
        step('Lire avant de sélectionner', 'Review before selecting', 'Détails explique la durée, les sources et les informations disponibles. Voir plus ajoute une page ; Voir moins revient aux résultats précédents sans relancer la recherche. Aucun résultat n’est inventé.', 'Details explains duration, sources and available information. Show more adds a page; Show less returns to previous results without searching again. Results are never invented.'),
        step('Utiliser ce vol', 'Use this flight', 'La sélection transfère les valeurs disponibles vers Votre vol. Les valeurs manuelles absentes du résultat sont conservées. Vérifiez l’avion et sa variante, les portes et pistes avant de préparer le carburant ou le message.', 'Selection transfers available values to Your flight. Manual values missing from the result are retained. Check aircraft and variant, gates and runways before preparing fuel or a message.')
    ]},
    {'id': 'fuel', 'title': pair('Fuel Helper', 'Fuel Helper'), 'steps': [
        step('Pour RFS uniquement', 'For RFS only', 'Cet outil utilise les références et formules de la version PC pour la simulation. Il ne convient pas à la préparation d’un vol réel. Aucun calcul ne nécessite Internet.', 'This tool uses the PC reference data and formulas for simulation. It is unsuitable for real flight planning. Calculations need no Internet access.'),
        step('Vérifier la variante', 'Check the variant', 'L’avion, la durée totale et l’arrivée du vol actuel sont repris lorsqu’ils sont reconnus. Cherchez une variante précise si le modèle est ambigu. Une modification d’avion nécessite un nouveau calcul.', 'The current aircraft, total duration and arrival are reused when recognised. Search for an exact variant if the model is ambiguous. Changing aircraft requires a new calculation.'),
        step('Comprendre les réserves', 'Understand reserves', 'Le résultat détaille roulage, trajet, marge, dégagement et réserve finale. Le dégagement est statique et choisi dans la référence disponible ; il ne tient pas compte de la météo ou des NOTAM. Consultez la provenance et les avertissements.', 'The result shows taxi, trip, contingency, alternate and final reserve. The alternate comes from a static reference; it does not consider weather or NOTAMs. Review provenance and warnings.'),
        step('Appliquer au vol', 'Apply to your flight', 'Appliquer avion + carburant met à jour le vol actuel avec la variante calculée et le carburant. Revenez au vol pour relire les valeurs, puis créez un message si vous en avez besoin.', 'Apply aircraft + fuel updates your current flight with the calculated variant and fuel. Return to your flight to review values, then create a message if needed.')
    ]},
    {'id': 'map', 'title': pair('Carte', 'Map'), 'steps': [
        step('Une carte déjà à bord', 'A map already on board', 'La carte locale et ses frontières fonctionnent sans Internet. Le trajet représente un grand cercle indicatif ; il ne constitue pas le plan de vol réel.', 'The local map and borders work without Internet. The route is an indicative great circle, not the actual flight plan.'),
        step('Se déplacer et zoomer', 'Pan and zoom', 'Faites glisser la carte, utilisez les boutons + et − ou pincez sur téléphone. Recentrer retrouve le trajet. Un niveau de zoom élevé n’ajoute pas de détails absents des données locales.', 'Drag the map, use + and − or pinch on your phone. Fit brings the route back into view. Higher zoom cannot add details missing from the local data.'),
        step('Du pays au vol', 'From countries to a flight', 'Choisissez les pays de départ et d’arrivée, ou le mode de sélection sur la carte, puis Trouver ces vols. Les deux pays deviennent des filtres du Finder. Un trajet peut ne pas exister dans la base.', 'Choose origin and destination countries, or use the map selection mode, then Find these flights. Both countries become Finder filters. A route may not exist in the database.'),
        step('Satellite et vents sur demande', 'Satellite and winds on request', 'Ces vues optionnelles utilisent Internet lorsque vous les activez. Satellite utilise l’imagerie EOX ; les vents proviennent d’Open-Meteo au niveau de pression choisi. Ce sont des données réelles indicatives, pas les vents garantis de votre session RFS. La carte locale reste disponible sans connexion.', 'These optional views use Internet when enabled. Satellite uses EOX imagery; winds come from Open-Meteo at the selected pressure level. They are indicative real-world data, not guaranteed winds in your RFS session. The local map remains available offline.')
    ]},
    {'id': 'library', 'title': pair('Bibliothèque', 'Library'), 'steps': [
        step('Retrouver votre travail', 'Find your work', 'Le vol actuel et vos réglages sont sauvegardés automatiquement. Enregistrer un vol crée aussi une copie nommée dans la bibliothèque pour le rappeler plus tard.', 'Your current flight and settings are saved automatically. Saving a flight also creates a named copy in the library for later recall.'),
        step('Vols, favoris et pilotes', 'Flights, favourites and pilots', 'Un vol sauvegardé garde ses informations. Un favori sert à rappeler une configuration de message. Les pilotes connus conservent leurs préférences pour éviter de les ressaisir.', 'A saved flight retains its information. A favourite recalls a message configuration. Known pilots keep their preferences so you do not have to enter them again.'),
        step('Votre historique reste local', 'Your history stays local', 'Les messages copiés apparaissent dans l’historique. Dupliquer rappelle les informations pour préparer un nouveau message. Le regroupement de petites corrections évite les doublons rapprochés.', 'Copied messages appear in history. Duplicate recalls their information to prepare a new message. Compact corrections groups closely spaced small changes.'),
        step('Partager une sauvegarde entre vos appareils', 'Share a backup between your devices', 'Exportez une sauvegarde depuis Aide sur PC ou Paramètres sur Android, puis importez-la sur l’autre appareil. Fusionner garde votre vol actuel et les éléments des deux appareils ; Remplacer restaure la sauvegarde choisie. Une copie de récupération est conservée avant l’import. Ce transfert est manuel : aucune synchronisation automatique n’est activée.', 'Export a backup from Help on PC or Settings on Android, then import it on the other device. Merge keeps your current flight and records from both devices; Replace restores the selected backup. A recovery copy is kept before import. This is a manual transfer: no automatic synchronisation is enabled.')
    ]},
    {'id': 'settings', 'title': pair('Paramètres', 'Settings'), 'steps': [
        step('Une interface à votre goût', 'An interface to your taste', 'Choisissez français ou anglais, mode clair ou sombre et l’une des dix palettes. Les données saisies restent les vôtres : changer de langue ne traduit pas le texte que vous avez écrit.', 'Choose French or English, light or dark mode and one of ten palettes. Entered data stays yours: changing language does not translate text you wrote.'),
        step('Sur téléphone', 'On your phone', 'Le menu devient une croix dans les paramètres : appuyez dessus pour revenir à votre écran précédent. Trois icônes Android sont disponibles. Les rappels locaux se programment à votre demande ; aucune météo ni recherche n’est lancée en arrière-plan.', 'The menu becomes a cross in settings: tap it to return to your previous screen. Three Android icons are available. Local reminders are scheduled at your request; no background weather or flight searches run.'),
        step('Designs et signalements', 'Designs and reports', 'Créez un design avec le guide ou les champs disponibles. Pour signaler un problème, décrivez ce qui se passe et joignez seulement les images souhaitées. Le rapport local n’est jamais envoyé automatiquement.', 'Create a design with the guide or available fields. To report an issue, describe what happens and attach only images you choose. A local report is never sent automatically.'),
        step('Aide et mises à jour', 'Help and updates', 'Passez ce tutoriel si vous le souhaitez : il reste dans Aide ou les paramètres, avec les trente questions hors ligne. Vérifier les mises à jour consulte seulement les versions publiques sur GitHub, sans envoyer vos vols. La vérification automatique est facultative, désactivée au départ et limitée à une tentative par jour. Vous choisissez le téléchargement et l’installation.', 'Skip this tutorial if you wish: it stays in Help or settings with thirty offline questions. Check for updates reads public GitHub releases without sending your flights. Automatic checking is optional, initially disabled and limited to one attempt a day. You choose whether to download and install.')
    ]}
]


_FAQ = [
    ('À quoi sert Flightdeck ?', 'What is Flightdeck for?', 'Préparer un vol RFS, chercher un profil historique, calculer le carburant et rédiger un message si vous utilisez l’ATC.', 'Prepare an RFS flight, find a historical profile, calculate fuel and write a message if you use ATC.'),
    ('Puis-je préparer un vol sans ATC ?', 'Can I prepare a flight without ATC?', 'Oui. Votre vol, Finder, carte et Fuel Helper sont utilisables sans générer de message.', 'Yes. Your flight, Finder, map and Fuel Helper work without generating a message.'),
    ('Faut-il un compte ?', 'Do I need an account?', 'Non. Les données restent sur votre appareil et aucune télémétrie n’est ajoutée.', 'No. Data stays on your device and there is no telemetry.'),
    ('Que puis-je utiliser en mode avion ?', 'What works in airplane mode?', 'Les messages, la base Finder, le calcul carburant, la carte locale, les sauvegardes et cette aide sur PC et Android. Satellite, vents réels, formulaire en ligne et vérification des mises à jour nécessitent une connexion. Une vérification indisponible ne bloque jamais vos outils locaux.', 'Messages, the Finder database, fuel calculation, local map, backups and this help on PC and Android. Satellite, real-world winds, online feedback and update checks need a connection. An unavailable check never blocks local tools.'),
    ('Comment installer ou mettre à jour Android ?', 'How do I install or update Android?', 'Téléchargez l’APK depuis un lien vérifié, ouvrez-la et autorisez cette source si Android le demande. Pour mettre à jour, installez la nouvelle APK par-dessus l’ancienne sans désinstaller ; elle doit garder la même signature. Exportez une sauvegarde avant. Vérifier les mises à jour signale seulement les versions publiques compatibles, pas les fichiers de test GitHub Actions.', 'Download the APK from a verified link, open it and allow that source if Android asks. To update, install the new APK over the existing app without uninstalling; it must keep the same signature. Export a backup first. Check for updates announces compatible public releases, not GitHub Actions test files.'),
    ('Comment lancer sur Windows ?', 'How do I start on Windows?', 'Extrayez entièrement le ZIP, puis ouvrez RFSATCMessageMaker.exe dans le dossier extrait. Gardez ses fichiers voisins. Le nom affiché dans l’application est RFS Flightdeck.', 'Extract the entire ZIP, then open RFSATCMessageMaker.exe in the extracted folder. Keep its neighbouring files. The displayed app name is RFS Flightdeck.'),
    ('Et sur iPhone ?', 'What about iPhone?', 'L’APK fonctionne seulement sur Android. Le prototype web fonctionne dans Safari mais reste incomplet, sans Finder local équivalent. Une vraie version iOS demande une adaptation du moteur, un Mac avec Xcode et des tests sur iPhone. Aucune application iOS équivalente ni distribution TestFlight n’est livrée actuellement.', 'The APK only works on Android. The web prototype works in Safari but is incomplete, without an equivalent local Finder. A real iOS version needs an adapted engine, a Mac with Xcode and iPhone tests. No equivalent iOS app or TestFlight distribution is currently delivered.'),
    ('Pourquoi certains vols manquent-ils ?', 'Why are some flights missing?', 'Finder contient des observations historiques limitées à sa base. Il ne crée pas de vols fictifs et ne représente pas toutes les lignes actuelles.', 'Finder contains historical observations limited to its database. It creates no fictional flights and does not represent all current routes.'),
    ('Pourquoi la durée est-elle estimée ?', 'Why is the duration estimated?', 'Certaines durées viennent de traces complètes, d’autres d’une estimation liée à la distance. Détails indique la provenance et les limites.', 'Some durations come from complete tracks, others from a distance estimate. Details shows provenance and limitations.'),
    ('Comment chercher dix heures minimum ?', 'How do I search for at least ten hours?', 'Dans Finder, saisissez 10 dans la durée minimum. 10h et 10:00 sont aussi acceptés ; utilisez min pour exprimer des minutes.', 'In Finder, enter 10 as the minimum duration. 10h and 10:00 also work; use min to express minutes.'),
    ('Comment choisir les pays ?', 'How do I choose countries?', 'Ouvrez le sélecteur et recherchez un nom ou un code. Sur la carte, choisissez les deux pays puis lancez Trouver ces vols.', 'Open the picker and search by name or code. On the map, choose both countries then use Find these flights.'),
    ('Utiliser ce vol efface-t-il mes valeurs ?', 'Does Use this flight erase my values?', 'Il remplace les informations fournies par le résultat. Les valeurs manuelles que Finder ne fournit pas sont conservées ; relisez-les pour le nouveau vol.', 'It replaces values supplied by the result. Manual values Finder does not supply are retained; review them for the new flight.'),
    ('Puis-je changer d’avion ?', 'Can I change aircraft?', 'Oui. Ouvrez la liste dans Votre vol et recherchez le modèle RFS. Les variantes restent séparées ; recalculez le carburant après une modification.', 'Yes. Open the list in Your flight and search for the RFS model. Variants remain separate; recalculate fuel after a change.'),
    ('Pourquoi l’avion n’est-il pas repris dans Fuel ?', 'Why is my aircraft not selected in Fuel?', 'Le nom doit correspondre à une variante connue. En cas d’ambiguïté, choisissez la variante proposée ; l’application ne devine pas une configuration incompatible.', 'The name must match a known variant. If ambiguous, choose a suggested variant; the app does not guess an incompatible configuration.'),
    ('Les calculs sont-ils prévus pour un vrai vol ?', 'Are calculations intended for real flights?', 'Non. Fuel Helper et les outils de préparation sont destinés à RFS et à la simulation uniquement.', 'No. Fuel Helper and preparation tools are for RFS and simulation only.'),
    ('Comment le dégagement est-il choisi ?', 'How is the alternate chosen?', 'Le calcul utilise la référence statique de la version PC. Aucun contrôle météo, NOTAM ou disponibilité réelle n’est effectué.', 'The calculation uses the PC static reference. It performs no weather, NOTAM or real availability checks.'),
    ('ETE 5 min signifie quoi ?', 'What does ETE 5 min mean?', 'Dans le message ARRIVAL BOARD, l’arrivée est prévue dans environ cinq minutes. Ce n’est pas la durée totale du vol.', 'In ARRIVAL BOARD, arrival is expected in about five minutes. It is not the total flight duration.'),
    ('Quels messages sont disponibles ?', 'Which messages are available?', 'La base PC propose ATC REQUEST, AIRBORNE, ARRIVAL BOARD, FLIGHT COMPLETED, DISPATCH FORM, ATC ACTIVE, ATC OFFLINE et FLIGHT PLAN. Android ajoute PUSHBACK, TAXI et ATIS.', 'The PC base offers ATC REQUEST, AIRBORNE, ARRIVAL BOARD, FLIGHT COMPLETED, DISPATCH FORM, ATC ACTIVE, ATC OFFLINE and FLIGHT PLAN. Android adds PUSHBACK, TAXI and ATIS.'),
    ('Comment ajouter plusieurs pilotes ?', 'How do I add multiple pilots?', 'Dans Votre vol, ouvrez les options pilotes. Ajoutez leurs noms et préférences puis choisissez l’opération en groupe ou décalée selon les champs disponibles.', 'In Your flight, open pilot options. Add names and preferences, then choose group or staggered operations using the available fields.'),
    ('Comment changer le design ?', 'How do I change the design?', 'Ouvrez Présentation dans Messages pour les designs intégrés, longueurs et emojis. Sur Android, créez les designs personnels dans Paramètres.', 'Open Presentation in Messages for built-in designs, lengths and emojis. On Android, create custom designs in Settings.'),
    ('Pourquoi des avertissements apparaissent-ils ?', 'Why do warnings appear?', 'Ils signalent les champs requis, valeurs incorrectes ou limites du message. Appuyez dessus pour aller au champ ou à l’aperçu concerné.', 'They identify required fields, incorrect values or message limits. Tap them to go to the relevant field or preview.'),
    ('Puis-je copier un message incomplet ?', 'Can I copy an incomplete message?', 'Oui : désactivez Vérifier avant copie. Les avertissements restent visibles. Le texte doit contenir au moins un caractère autre qu’un espace.', 'Yes: disable Check before copying. Warnings remain visible. Text must contain at least one non-whitespace character.'),
    ('Pourquoi compter les caractères et emojis ?', 'Why count characters and emojis?', 'Le contrôle signale les messages dépassant 2 000 caractères et plus de six emojis, sauf DISPATCH FORM pour les emojis. La copie libre permet de garder votre texte avec ces avertissements.', 'Checks flag messages over 2,000 characters and more than six emojis, except DISPATCH FORM for emojis. Free copying lets you keep the text with these warnings.'),
    ('Puis-je retoucher l’aperçu ?', 'Can I edit the preview?', 'Oui. Une nouvelle génération ou un changement des champs source peut remplacer vos retouches. Copier conserve le message dans l’historique.', 'Yes. Regeneration or changing source fields can replace edits. Copying retains the message in history.'),
    ('Mes informations restent-elles après fermeture ?', 'Does my information survive closing?', 'Oui, les applications Windows et Android enregistrent localement le vol actuel et les réglages. Attendez l’indication de sauvegarde sur téléphone et exportez avant une désinstallation.', 'Yes, Windows and Android save the current flight and settings locally. Wait for the saved indication on your phone and export before uninstalling.'),
    ('Comment retrouver mes données sur PC et téléphone ?', 'How do I share data between PC and phone?', 'Exportez la sauvegarde JSON depuis Aide sur PC ou Paramètres sur Android, transmettez le fichier à l’autre appareil et importez-le. Relisez le résumé puis choisissez Fusionner ou Remplacer. Fusionner garde le vol actuel et les éléments différents des deux appareils. Un import conserve une copie de récupération et n’active pas les connexions facultatives de l’autre appareil. Android accepte aussi les quatre anciens fichiers PC sélectionnés ensemble. Il n’y a pas encore de synchronisation automatique.', 'Export the JSON backup from Help on PC or Settings on Android, transfer the file to the other device and import it. Review the summary, then choose Merge or Replace. Merge keeps the current flight and differing records from both devices. Import keeps a recovery copy and does not enable the other device’s optional connections. Android also accepts the four legacy PC files selected together. Automatic synchronisation is not available yet.'),
    ('Les vents correspondent-ils à RFS ?', 'Do winds match RFS?', 'Ils sont issus d’une météo réelle indicative au niveau de pression choisi. La météo du jeu peut différer ; ils ne garantissent pas votre temps de vol.', 'They are indicative real-world weather at the selected pressure level. Game weather may differ; they do not guarantee flight time.'),
    ('Pourquoi aucune porte n’est-elle proposée ?', 'Why is no gate suggested?', 'La base ne contient pas les portes ni leur affectation par compagnie. Choisissez dans RFS. Les pistes listées ne sont pas des autorisations de départ.', 'The database has no gates or airline gate assignments. Choose in RFS. Listed runways are not departure clearances.'),
    ('Puis-je personnaliser les rappels et l’apparence ?', 'Can I customise reminders and appearance?', 'PC et Android ont dix palettes en clair et sombre. Android propose trois icônes et un rappel local volontaire. Après Forcer l’arrêt, programmez à nouveau le rappel.', 'PC and Android have ten palettes in light and dark modes. Android offers three icons and an optional local reminder. After Force stop, schedule the reminder again.'),
    ('Comment retrouver l’aide ou signaler un souci ?', 'How do I reopen help or report a problem?', 'Ouvrez Aide sur PC, Paramètres sur Android ou Aide sur le prototype web. Consultez ce tutoriel ou recherchez une question. Un rapport local peut inclure des images choisies ; il n’est jamais envoyé automatiquement.', 'Open Help on PC, Settings on Android or Help in the web prototype. Browse this tutorial or search for a question. A local report can include selected images; it is never sent automatically.')
]

FAQ = [{'id': f'faq-{i:02}', 'question': pair(a, b), 'answer': pair(c, d)}
       for i, (a, b, c, d) in enumerate(_FAQ, 1)]
CONTENT = {'version': 1, 'topics': TOPICS, 'faq': FAQ}
