const {go}=require('./navigation.cjs');
// Runs against ui_server.py. No browser-only backend ships in the APK.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const port=Number(process.argv[2]);
 const request=async(method,args={})=>(await(await fetch(`http://127.0.0.1:${port}/rpc`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({method,args})})).json());
 const boot=await request('bootstrap');assert(boot.ok);
 boot.result.value.state.language='fr';
 assert((await request('save',{state:boot.result.value.state})).ok);
 const browser=await chromium.launch({headless:true,...(process.env.RFS_TEST_BROWSER?{channel:process.env.RFS_TEST_BROWSER}:{})});
 const page=await browser.newPage({viewport:{width:390,height:844}});
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.exposeFunction('testRequest',async(id,method,payload)=>{
  const response=await fetch(`http://127.0.0.1:${port}/rpc`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({method,args:JSON.parse(payload)})});
  const envelope=await response.json();
  await page.evaluate(({id,envelope})=>window.androidReply(id,envelope),{id,envelope});
 });
 await page.addInitScript(()=>{window.Android={request:(id,method,payload)=>window.testRequest(id,method,payload)};});
 await page.goto(`http://127.0.0.1:${port}/index.html`);
 await page.locator('[data-action="welcome-joke"]').click();
 await page.waitForFunction(()=>document.querySelector('main').textContent.includes('Les 999 € étaient une blague'));
 await page.locator('[data-action="welcome-done"]').click();await page.locator('.fd-help [data-help="close"]').first().click();
 await page.locator('#flight-callsign').fill('MOBILE123');
 await page.locator('#flight-departure_icao').fill('LFPG');
 await page.locator('.flight-flags summary').click();
 await page.locator('[data-action="country-open"][data-target="flight-departure_flag"]').click();
 await page.locator('#country-search').fill('France');
 await page.locator('[data-action="country-select"][data-code="FR"]').click();
 await page.waitForFunction(()=>model.state.flight.departure_flag==='🇫🇷');
 await go(page,'messages');
 await page.locator('#state-message_type').selectOption('ATC ACTIVE');
 await page.locator('#message-airport_icao').fill('LFPG');
 await page.locator('#message-city').fill('Paris');
 await page.locator('#message-positions').fill('Tower');
 await page.locator('[data-action="generate"]').click();
 await page.locator('#preview').waitFor();
 await page.waitForFunction(()=>rendered.can_copy);
 await page.locator('#preview').fill('USER PREVIEW last character Z');
 await page.waitForFunction(()=>rendered.preview.includes('last character Z'));
 await page.locator('#copy').click();
 await page.waitForFunction(()=>model.history.length===1);
 assert((await page.evaluate(()=>model.history[0].message)).includes('last character Z'));
 await go(page,'flight');
 assert.equal(await page.locator('#flight-callsign').inputValue(),'MOBILE123');
 await go(page,'finder');
 await page.locator('#finder-origin').fill('LFPG');
 await page.locator('#finder-max_minutes').fill('2h');
 await page.locator('#search').click();
 await page.waitForFunction(()=>finderRows.length===100);
 await page.locator('#more').click();
 await page.waitForFunction(()=>finderRows.length===200);
 await page.locator('#less').click();
 await page.waitForFunction(()=>finderVisible===100);
 await page.locator('#more').click();
 await page.waitForFunction(()=>finderVisible===200);
 await page.locator('#result-100 [data-action="finder-use"]').click();
 await page.locator('#flight-departure_icao').waitFor();
 assert.equal(await page.locator('#flight-departure_icao').inputValue(),'LFPG');
 await page.locator('[data-action="flight-aircraft-open"]').click();
 await page.locator('#flight-aircraft-search').fill('A220');
 await page.locator('[data-action="flight-aircraft-select"][data-id="airbus_a220_300"]').click();
 await go(page,'fuel');
 await page.locator('#aircraft-search').waitFor();
 assert.equal(await page.evaluate(()=>model.state.fuel_inputs.aircraft),'airbus_a220_300');
 await page.locator('#aircraft-search').fill('A220');
 await page.locator('[data-action="fuel-aircraft"][data-id="airbus_a220_300"]').click();
 await page.locator('#fuel-duration').fill('5h');
 await page.locator('#fuel-arrival').fill('EGLL');
 await page.locator('[data-action="fuel-calculate"]').click();
 await page.locator('[data-action="fuel-use"]').waitFor();
 assert.equal(await page.locator('#fuel-result .stat').textContent(),'12,285 kg');
 await page.screenshot({path:process.argv[3]||'build/ux-ui-fuel.png',fullPage:true});
 await page.locator('[data-action="fuel-use"]').click();
 await page.locator('#flight-callsign').waitFor();
 await page.reload();
 await page.locator('#flight-callsign').waitFor();
 assert.equal(await page.evaluate(()=>model.state.flight.fuel),'12285');
 // The map must work with no remote resource requests.
 const remote=[];page.on('request',request=>{if(!request.url().startsWith(`http://127.0.0.1:${port}/`))remote.push(request.url());});
 await page.locator('#flight-arrival_icao').fill('KJFK');
 await go(page,'map');
 await page.waitForFunction(()=>countryGeometry?.length===242&&mobileMap?.data.route.length===97);
 const country=await page.evaluate(()=>{const lat=48.8566,lon=2.3522,s=mobileMap.scale(),p=[mobileMap.canvas.clientWidth/2+(lon-mobileMap.center[0])*s,mobileMap.canvas.clientHeight/2+(MapProjection.y(lat)-mobileMap.center[1])*s];return mobileMap.countryAt(p);});
 assert.equal(country,'FR');
 const initialZoom=await page.evaluate(()=>mobileMap.zoom);
 await page.locator('[data-action="map-plus"]').click();
 assert((await page.evaluate(()=>mobileMap.zoom))>initialZoom);
 // Pinch preserves an anchored point while changing scale.
 await page.evaluate(()=>{const el=mobileMap.canvas,r=el.getBoundingClientRect(),event=(type,id,x)=>new PointerEvent(type,{pointerId:id,pointerType:'touch',clientX:r.left+x,clientY:r.top+120,bubbles:true});
  // Synthetic events cannot capture an inactive pointer; exercise the same
  // gesture handlers with pointer capture omitted solely in this browser test.
  const capture=el.setPointerCapture;el.setPointerCapture=()=>{};
  mobileMap.down(event('pointerdown',1,100));mobileMap.down(event('pointerdown',2,200));
  mobileMap.move(event('pointermove',2,250));mobileMap.up(event('pointerup',1,100));mobileMap.up(event('pointerup',2,250));el.setPointerCapture=capture;});
 assert((await page.evaluate(()=>mobileMap.zoom))>initialZoom*1.6);
 await page.locator('[data-action="map-fit"]').click();
 await page.locator('#map-origin').selectOption('FR');
 await page.locator('#map-destination').selectOption('RO');
 await page.screenshot({path:(process.argv[3]||'build/ux-ui-fuel.png').replace(/\.png$/, '-map.png'),fullPage:true});
 const view=await page.evaluate(()=>JSON.parse(JSON.stringify(model.state.map_settings)));
 await page.reload();await go(page,'map');
 await page.waitForFunction(()=>mobileMap?.data.route.length===97);
 assert.deepEqual(await page.evaluate(()=>model.state.map_settings),view);
 await page.locator('[data-action="map-finder"]').click();
 await page.waitForFunction(()=>finderResponse&&!finderBusy);
 assert.equal(await page.evaluate(()=>model.state.finder_filters.origin_country),'FR');
 assert.equal(await page.evaluate(()=>model.state.finder_filters.destination_country),'RO');
 assert.equal(await page.evaluate(()=>model.state.finder_filters.origin),'');
 assert.deepEqual(remote,[]);
 // Libraries: rename/delete without changing the current flight, remembered
 // pilot preferences, and deletion of the currently selected custom design.
 let reply='Phone route';page.on('dialog',dialog=>dialog.accept(reply));
 await go(page,'flight');
 await page.locator('[data-action="save-flight"]').click();
 await page.waitForFunction(()=>model.state.saved_flights.length===1);
 await go(page,'library');
 reply='Renamed route';await page.locator('[data-action="library-rename"][data-category="flights"]').click();
 await page.waitForFunction(()=>model.state.saved_flights[0].label==='Renamed route');
 await page.locator('[data-action="library-pilot-new"]').click();
 await page.locator('#library-pilot-name').fill('Wing');
 await page.locator('#library-pilot-callsign').fill('WING123');
 await page.locator('[data-action="library-pilot-save"]').click();
 await page.waitForFunction(()=>model.state.pilot_library.some(p=>p.name==='Wing'));
 await page.locator('[data-action="library-pilot-edit"]').click();
 await page.locator('#library-pilot-callsign').fill('WING456');
 await page.locator('[data-known-type="ATC REQUEST"]').uncheck();
 await page.locator('[data-action="library-pilot-save"]').click();
 await page.locator('[data-action="library-delete"][data-category="flights"]').click();
 await page.waitForFunction(()=>model.state.saved_flights.length===0);
 assert.equal(await page.evaluate(()=>model.state.flight.arrival_icao),'KJFK');
 await page.reload();await go(page,'library');
 assert.equal(await page.evaluate(()=>model.state.pilot_library[0].callsign),'WING456');
 assert(!(await page.evaluate(()=>model.state.pilot_library[0].message_types)).includes('ATC REQUEST'));
 await go(page,'flight');
 await page.locator('summary').filter({hasText:'Pilotes et opérations'}).click();
 await page.locator('#known-pilot').selectOption('0');
 await page.locator('[data-action="recall-pilot"]').click();
 await page.waitForFunction(()=>model.state.flight.pilots.length===1);
 assert.equal(await page.evaluate(()=>model.state.flight.pilots[0].callsign),'WING456');
 assert(!(await page.evaluate(()=>model.state.flight.pilots[0].message_types)).includes('ATC REQUEST'));
 await page.locator('#pilot-0-callsign').fill('WING789');
 await page.waitForFunction(()=>model.state.pilot_library[0].callsign==='WING789');
 assert(!(await page.evaluate(()=>model.state.pilot_library[0].message_types)).includes('ATC REQUEST'));
 await go(page,'library');
 reply='Phone favourite';await page.locator('[data-action="save-preset"]').click();
 await page.waitForFunction(()=>Boolean(model.presets['Phone favourite']));
 reply='Renamed favourite';await page.locator('[data-action="library-rename"][data-category="presets"]').click();
 await page.waitForFunction(()=>Boolean(model.presets['Renamed favourite']));
 await page.locator('[data-action="library-delete"][data-category="presets"]').click();
 await page.waitForFunction(()=>Object.keys(model.presets).length===0);
 await page.locator('#settings-open').click();
 if(!await page.locator('summary').filter({hasText:'Designs personnels'}).locator('..').evaluate(el=>el.open))await page.locator('summary').filter({hasText:'Designs personnels'}).click();
 await page.locator('#design-name').fill('Phone design');
 await page.locator('#design-heading').fill('PHONE HEADING');
 await page.locator('[data-action="save-design"]').click();
 await page.waitForFunction(()=>Object.keys(model.designs).length===1);
 await go(page,'library');
 await page.locator('[data-action="library-design-edit"]').click();
 if(!await page.locator('summary').filter({hasText:'Designs personnels'}).locator('..').evaluate(el=>el.open))await page.locator('summary').filter({hasText:'Designs personnels'}).click();
 assert.equal(await page.locator('#design-heading').inputValue(),'PHONE HEADING');
 await go(page,'library');
 await page.locator('[data-action="library-delete"][data-category="designs"]').click();
 await page.waitForFunction(()=>Object.keys(model.designs).length===0);
 assert.equal(await page.evaluate(()=>model.state.presentation.custom_id),'');
 await page.locator('#settings-open').click();
 await page.locator('#state-language').selectOption('en');
 await page.waitForFunction(()=>meta.flight_fields.airline.label==='Airline');
 assert.equal(await page.locator('h1').textContent(),'Settings');
 assert.deepEqual(errors,[]);
 console.log('PASS: phone UI, validation/copy, Finder pages/transfer, aircraft→Fuel, offline map/242 borders/97 route points/zoom/pinch/persistence/countries→Finder, library rename/delete, pilot preferences/restart, FR→EN');
 await browser.close();
})().catch(error=>{console.error(error);process.exit(1);});
