// Runs against ui_server.py. No browser-only backend ships in the APK.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const port=Number(process.argv[2]);
 const browser=await chromium.launch({headless:true,...(process.env.RFS_TEST_BROWSER?{channel:process.env.RFS_TEST_BROWSER}:{})});
 const page=await browser.newPage({viewport:{width:390,height:844}});
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.exposeFunction('testRequest',async(id,method,payload)=>{
  const response=await fetch(`http://127.0.0.1:${port}/rpc`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({method,args:JSON.parse(payload)})});
  const envelope=await response.json();
  await page.evaluate(({id,envelope})=>window.androidReply(id,envelope),{id,envelope});
 });
 await page.addInitScript(()=>{window.Android={request:(id,method,payload)=>window.testRequest(id,method,payload)};});
 await page.goto(`http://127.0.0.1:${port}/index.html`);
 await page.locator('[data-action="welcome-done"]').click();
 await page.locator('#flight-callsign').fill('MOBILE123');
 await page.locator('#flight-departure_icao').fill('LFPG');
 await page.locator('[data-screen="messages"]').click();
 await page.locator('#state-message_type').selectOption('ATC ACTIVE');
 await page.locator('#message-airport_icao').fill('LFPG');
 await page.locator('#message-city').fill('Paris');
 await page.locator('#message-positions').fill('Tower');
 await page.locator('[data-action="generate"]').click();
 await page.locator('#preview').waitFor();
 await page.waitForFunction(()=>rendered.can_copy);
 await page.locator('#preview').fill('USER PREVIEW last character Z');
 await page.waitForFunction(()=>rendered.preview.includes('last character Z'));
 await page.locator('#copy').click();
 await page.waitForFunction(()=>model.history.length===1);
 assert((await page.evaluate(()=>model.history[0].message)).includes('last character Z'));
 await page.locator('[data-screen="flight"]').click();
 assert.equal(await page.locator('#flight-callsign').inputValue(),'MOBILE123');
 await page.locator('[data-screen="finder"]').click();
 await page.locator('#finder-origin').fill('LFPG');
 await page.locator('#finder-max_minutes').fill('2h');
 await page.locator('#search').click();
 await page.waitForFunction(()=>finderRows.length===100);
 await page.locator('#more').click();
 await page.waitForFunction(()=>finderRows.length===200);
 await page.locator('#result-100 [data-action="finder-use"]').click();
 await page.locator('#flight-departure_icao').waitFor();
 assert.equal(await page.locator('#flight-departure_icao').inputValue(),'LFPG');
 await page.locator('[data-screen="fuel"]').click();
 await page.locator('#aircraft-search').fill('A220');
 await page.locator('[data-action="fuel-aircraft"][data-id="airbus_a220_300"]').click();
 await page.locator('#fuel-duration').fill('5h');
 await page.locator('#fuel-arrival').fill('EGLL');
 await page.locator('[data-action="fuel-calculate"]').click();
 await page.locator('[data-action="fuel-use"]').waitFor();
 assert.equal(await page.locator('#fuel-result .stat').textContent(),'12,285 kg');
 await page.screenshot({path:process.argv[3]||'android-fuel-ui.png',fullPage:true});
 await page.locator('[data-action="fuel-use"]').click();
 await page.locator('#flight-callsign').waitFor();
 await page.reload();
 await page.locator('#flight-callsign').waitFor();
 assert.equal(await page.evaluate(()=>model.state.flight.fuel),'12285');
 await page.locator('#settings-open').click();
 await page.locator('#state-language').selectOption('en');
 await page.waitForFunction(()=>meta.flight_fields.airline.label==='Airline');
 assert.equal(await page.locator('h1').textContent(),'Settings');
 assert.deepEqual(errors,[]);
 console.log('PASS: phone UI navigation, validation, edited copy payload, Finder 100→200/transfer, A220 fuel, reload persistence, FR→EN');
 await browser.close();
})().catch(error=>{console.error(error);process.exit(1);});
